name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: ASDF plugin test
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: asdf-vm/actions/plugin-test@v1
        with:
          command: grain --version
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
